export default {
  PROGRESS_CONTROLLER: 'bizMOB/PROGRESS_CONTROLLER',
  APPLICATION_EXIT: 'bizMOB/APPLICATION_EXIT',
  SET_SESSION_TIMEOUT: 'bizMOB/SET_SESSION_TIMEOUT',
  GET_REGISTERED_CALL_IDS: 'bizMOB/GET_REGISTERED_CALL_IDS'
};
