export default {
  GET_DEVICE_INFO: 'bizMOB/GET_DEVICE_INFO',
  SET_DEVICE_INFO: 'bizMOB/SET_DEVICE_INFO',
  IS_IOS: 'bizMOB/IS_IOS',
  IS_ANDROID: 'bizMOB/IS_ANDROID',
  IS_PHONE: 'bizMOB/IS_PHONE',
  IS_TABLET: 'bizMOB/IS_TABLE'
};
