export default {
  TEL: 'bizMOB/TEL',
  SMS: 'bizMOB/SMS',
  SHOW_WEBSITE: 'bizMOB/SHOW_WEBSITE',
  GET_MEDIA_PICK: 'bizMOB/GET_MEDIA_PICK',
  SHOW_MAP: 'bizMOB/SHOW_MAP',
  GET_LOCATION: 'bizMOB/GET_LOCATION',
  CAMERA_CAPTURE: 'bizMOB/CAMERA_CAPTURE'
};
