export default {
  SHOW_MESSAGE: 'bizMOB/SHOW_MESSAGE',
  GOTO_SIGNATURE: 'bizMOB/GOTO_SIGNATURE',
  OPEN_FILE_BROWSER: 'bizMOB/OPEN_FILE_BROWSER',
  SHOW_IMAGE_VIEW: 'bizMOB/SHOW_IMAGE_VIEW',
  QR_AND_BAR_CODE: 'bizMOB/QR_AND_BAR_CODE'
};
